name: Deploy Website SMKN 1 Leuwimunding

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Menampilkan daftar file website
        run: ls

      - name: Deploy Berhasil
        run: echo "Website Profil SMKN 1 Leuwimunding berhasil di deploy!"